name: ddgr
adopt-info: ddgr
summary: DuckDuckGo from the terminal
description: |
  ddgr is a cmdline utility to search DuckDuckGo from the terminal. While 
  googler is highly popular among cmdline users, in many forums the need 
  of a similar utility for privacy-aware DuckDuckGo came up. DuckDuckGo 
  Bangs are super-cool too! So here's ddgr for you!
  Unlike the web interface, you can specify the number of search results 
  you would like to see per page. It's more convenient than skimming through 
  30-odd search results per page. The default interface is carefully designed 
  to use minimum space without sacrificing readability.
  ddgr isn't affiliated to DuckDuckGo in any way..
base: core22

grade: stable
confinement: strict

apps:
  ddgr:
    environment:
      LC_ALL: "C.UTF-8"
    command: usr/local/bin/ddgr
    plugs:
      - network
      - desktop

parts:
  ddgr:
    plugin: make
    source: https://github.com/jarun/ddgr.git
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_released_tag="$(snap info ddgr | awk '$1 == "latest/beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
    override-build: |
      snapcraftctl build
      # make install
      snapcraftctl set-version "$(git describe --dirty | sed 's/v//g')"
    stage-packages:
      - python3
      - python3-requests
    prime:
      # compilers and debuggers
      - -usr/bin/pdb3*
      # debhelper
      - -usr/bin/dh_*
      - -usr/share/debhelper
      - -usr/share/dh-python
      - -usr/share/perl5/Debian
      # docs
      - -usr/share/doc
      - -usr/share/doc-base
      # lintian
      - -usr/share/lintian/overrides
      # man pages
      - -usr/share/man
      - -share/man
      # meta
      - -usr/share/applications
      - -usr/share/pixmaps
      # python 2to3
      - -usr/bin/2to3*
      - -usr/lib/python*/lib2to3
      # python idle
      - -usr/lib/python*/idlelib
      - -usr/lib/python*/tkinter
      # python pip
      - -lib/python*/site-packages/pip
      # python setuptools
      - -lib/python*/site-packages/setuptools*
      # python tests
      - -lib/python*/site-packages/tests
      # python venv
      - -usr/lib/python*/venv
      # python wheel
      - -lib/python*/site-packages/wheel*
      # x11
      - -usr/share/X11/XErrorDB
